---
sidebar: sidebar 
permalink: reference_kpls.html 
keywords: 'what"s new, features, new, release notes, known, problems, limitations, application' 
summary: SaaS Backup pour Microsoft 365 inclut régulièrement une nouvelle version qui présente de nouvelles fonctionnalités, des améliorations et des correctifs. 
---
= Problèmes et limites connus
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les limitations connues suivantes, identifiées au niveau de l'application pour SaaS Backup pour Microsoft 365.



== Pour SharePoint Online

SaaS Backup ne prend pas en charge les sauvegardes des sites SharePoint archivés.



== Pour OneDrive entreprise

Les nouveaux lecteurs ajoutés ne sont pas détectés tant que vous n'avez pas effectué manuellement une synchronisation pour le service.



== Pour Exchange Online

* SaaS Backup ne prend pas en charge les sauvegardes des dossiers publics.
* *Recherche avancée* est uniquement disponible pour Exchange Online. Le paramètre est désactivé par défaut. Un client doit demander d'activer cette fonctionnalité. Une fois que le paramètre *Activer la recherche avancée* est activé, les administrateurs doivent activer manuellement la fonction de recherche pour les utilisateurs individuels.




== Pour les équipes

* La configuration du canal est restaurée, mais le contenu et les conversations ne le sont pas.
* En raison des limites des API, SaaS Backup ne peut pas faire la différence entre canaux publics et privés dans SaaS Backup.
* Restauration de haut niveau qui restaure les données de boîtes aux lettres et SharePoint uniquement, pas les données de conversation
* La sauvegarde ou la restauration des emojis et des pixels invisibles n'est pas prise en charge dans Teams Chat.
* L'option d'exportation des conversations en groupe uniquement est Exporter au format HTML. Les liens de pièce jointe publiés dans les conversations ne sont pas visibles dans le document html.




== Pour OneNote

* L'exportation vers les données n'est pas disponible.
* La tâche de sauvegarde incrémentielle peut échouer avec le message d'erreur suivant :
`Partial Failure. Failed to back up few OneNote Sections`.
* Les sauvegardes OneDrive incluent la sauvegarde des fichiers .onebak.
* Les statistiques de restauration ne sont pas disponibles au téléchargement.
* L'exportation et la purge des données ne sont pas prises en charge.




== Autres problèmes et limites

Les problèmes et limitations connus suivants ne sont pas spécifiques à une application.

Pour tous les utilisateurs qui s'abonnent à un compte de service Microsoft 365 :

* SaaS Backup prend uniquement en charge l'authentification de base.


Pour les utilisateurs d'essai gratuit :

* Un maximum de 10 restaurations par service est autorisé en 24 heures.


Pour les utilisateurs sous licence :

* Un maximum de 10 restaurations de données d'exportation par service sont autorisées sur une période de 24 heures. Toutes les autres options de restauration n'ont aucune limite.


Pour les restaurations de groupes de collecte de sites :

* Si un groupe de collecte de sites entier est supprimé, la restauration des groupes privés de la collection échoue, entraînant un état de restauration de la tâche de "partiellement en échec". Dans ce cas, le site n'est pas accessible à partir de l'interface utilisateur graphique.


Pour *recherche avancée* :

* Un maximum de 10 travaux de recherche sont autorisés sur une période de 24 heures.

