---
sidebar: sidebar 
permalink: task_adding_permissions_to_service_accounts.html 
keywords: netapp, saas backup, microsoft 365, add, adding, permissions, service, accounts 
summary: 'Si nécessaire, vous pouvez ajouter des comptes supplémentaires pour améliorer les performances de sauvegarde. Les comptes de service permettent d"effectuer des sauvegardes simultanées efficacement.' 
---
= Ajouter des comptes de service supplémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez, le cas échéant, ajouter des comptes de service supplémentaires pour améliorer les performances de sauvegarde. Les comptes de service permettent d'effectuer des sauvegardes simultanées efficacement.

.Étapes
. Connectez-vous au portail de gestion Microsoft 365 à l'aide d'un compte disposant de privilèges d'administration.
. Cliquez sur l'icône du programme de lancement de l'application, puis sur *Admin*.
. Sur la gauche, cliquez sur *utilisateurs*, puis sur *utilisateurs actifs*.
. Cliquez sur *Ajouter un utilisateur* pour créer un nouveau compte.
. Remplissez le formulaire en suivant les instructions ci-dessous.
+
** Utilisez *Permettez-moi de créer le mot de passe*.
** Désélectionnez *faire changer le mot de passe de cet utilisateur lorsqu'il se connecte à l'option* pour la première fois.
** Sélectionnez le rôle *Administrateur personnalisé*.
** Sélectionnez *Administrateur Exchange* et *Administrateur SharePoint*.
** Sélectionnez *Créer un utilisateur sans licence de produit*.


. Pour que les sauvegardes Exchange s'exécutent avec des comptes de service nouvellement créés, attribuez les droits d'emprunt d'identité Exchange à ces comptes de service nouvellement créés.link:task_configuring_impersonation.html["Configuration des usurpation d'identité"]



NOTE: La solution SaaS Backup attribue automatiquement les autorisations sur les sites OneDrive et SharePoint. Vous n'avez donc pas besoin de les attribuer.


NOTE: Vous pouvez activer l'autorisation multifacteur (MFA) sur ce compte.
