---
sidebar: sidebar 
permalink: task_completing_signing_up_ipa.html 
keywords: netapp, saas backup, microsoft 365, getting started, sign up, signing up, paid, subscription, licensed, version 
summary: Vous pouvez vous inscrire à SaaS Backup pour Microsoft 365 avec votre compte de service Microsoft 365 ou avec votre compte SSO NetApp. 
---
= Inscrivez-vous avec un abonnement payant
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si vous avez acheté votre licence via NetApp, vos types d'abonnement s'affichent. Effectuez le processus d'inscription en suivant ces étapes.

Pour valider votre abonnement, vous devez disposer d'un ID utilisateur et d'un mot de passe SSO. Si vous ne possédez pas de compte SSO NetApp, consultez le site https://mysupport.netapp.com/eservice/public/now.do[] pour vous inscrire pour un seul. Une fois votre demande traitée, vous recevrez une notification par e-mail contenant vos identifiants SSO de NetApp. Le traitement de la demande prendra environ 24 heures et l'envoi de l'e-mail de notification.

.Étapes
. Sélectionnez *sous licence* pour le type d'abonnement.
. Entrez les informations demandées, puis validez l'abonnement.
. Cliquez sur *Suivant*.
. Sélectionnez votre option de stockage de sauvegarde.
+
.. Cliquez sur *SaaS Backup fournis Storage*.
.. Sélectionnez l'option de stockage *Amazon S3* ou *Azure Blob*.
.. Sélectionnez la région *AWS S3* ou *Azure Blob* pour votre sauvegarde. Vous devez sélectionner la région la plus proche de l'emplacement physique des données que vous sauvegardez.
.. Cliquez sur *Suivant*.
.. Vérifiez votre configuration, puis cliquez sur *Enregistrer*.



